# ---
# - name: Install Docker
#   hosts: all
#   become: true

#   tasks:
#     - name: Update apt cache
#       ansible.builtin.apt:
#         update_cache: yes

#     - name: Install Docker
#       ansible.builtin.package:
#         name:
#           - docker.io
#         state: present

#     - name: Start and Enable Docker
#       ansible.builtin.service:
#         name: docker
#         state: started
#         enabled: true

#     - name: Add user to Docker group
#       ansible.builtin.user:
#         name: ubuntu
#         groups: docker
#         append: true
---
- name: Create Docker network
  ansible.builtin.docker_network:
    name: app_network
    state: present
  become: true      # Ensures elevated privileges if needed

# - name: Create Docker network
#   hosts: all
#   become: true

#   tasks:
#     - name: Create Docker network
#       ansible.builtin.docker_network:
#         name: app_network
#         state: present


- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker
  ansible.builtin.package:
    name:
      - docker.io
    state: present

- name: Start and Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to Docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
