global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: "prometheus"
    metrics_path: "prometheus/metrics"  # Correct metrics path for Prometheus
    static_configs:
      - targets: ["prometheus:9090"]  # Use internal Docker hostname      
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]  # Use Docker hostname for cAdvisor